mtb_version: 4
chip: sc5654a        # cb2201 / cb6501 / sc5654a
diff:
  digest_type: SHA1
  signature_type: RSA1024
  fota_version: 0
  ram_buf: 50      #DEC     KB   ( max ram need)
  flash_buf: 16     #DEC    KB   ( buffer size)
  flash_sector: 4096 #DEC   byte ( flash sector)
  diff_mode: 010    #BIN
  double_control: 1
flash:
  base_address: 0x00000000
  run_base_address: 0x02000000 # base address of Storage
  sector: 4096       # Bytes
  size: 8388608      # $(sector count) * sector
partitions:
  - { name: m0flash, address: 0x00000, size: 0x00070000 }
  - { name: boot, address: 0x00070000, size: 0x010000, load_addr: 0x02780000 }
  - { name: dsp,  address: 0x00080000, load_addr: 0x02000000, size: 0x200000, update: FULL }
  - { name: bmtb, address: 0x00280000, size: 0x001000 }
  - { name: imtb, address: 0x00281000, size: 0x002000 }
  - { name: prim, address: 0x00283000, load_addr: 0x02200000, size: 0x200000, update: FULL }
  - { name: kv,   address: 0x00483000, size: 0x004000 }
  - { name: misc, address: 0x00487000, size: 0x379000 }

