mtb_version: 4
chip: bl606

diff:
  fota_version: 0
  ram_buf: 4            #DEC     KB   ( max ram need)
  flash_buf: 16         #DEC     KB   ( buffer size)
  flash_sector: 4096    #DEC     byte ( flash sector)
  diff_mode: 010        #BIN
  double_control: 1
flash:
  base_address: 0               # 存储基地址，比如FLASH的基地址
  run_base_address: 0x54000000  # base address of Storage
  sector: 4096                  # Bytes
  size: 0x1000000          # $(sector count) * sector

partitions:
  - { name: bootmini, address: 0x000000, size: 0x011000, file: bootmini.bin }
  - { name: boot,     address: 0x011000, size: 0x020000, file: boot.bin }
  - { name: imtb,     address: 0x031000, size: 0x002000 }
  - { name: fct,      address: 0x033000, size: 0x004000 }
  - { name: envab,    address: 0x037000, size: 0x004000 } # for ab switch, size must be 2*sector+1024B at least
  - { name: prima,    address: 0x03C000, size: 0x57F000, load_addr: 0x54020000, file: prim, verify: true } # boliu flashtool will add 4KB header
  - { name: primb,    address: 0x5BB000, size: 0x57F000, load_addr: 0x54020000, verify: true }
  - { name: kv,       address: 0xB3A000, size: 0x020000 }
  - { name: lfs,      address: 0xB5A000, size: 0x491000 } # media
  - { name: dts,      address: 0xFEB000, size: 0x008000 }
  - { name: user,     address: 0xFF3000, size: 0x008000 }
  - { name: kp,       address: 0xFFB000, size: 0x001000 }

