mtb_version: 4
chip: d1

diff:
  fota_version: 0
  ram_buf: 50           #DEC     KB   ( max ram need)
  flash_buf: 16         #DEC     KB   ( buffer size)
  flash_sector: 4096    #DEC     byte ( flash sector)
  diff_mode: 010        #BIN
  double_control: 1
flash:
  base_address: 0         # 存储基地址，比如FLASH的基地址
  run_base_address: 0x40000000 # base address of Storage
  sector: 4096            # Bytes
  size: 16777216          # 4096 $(sector count) * sector

partitions:
  - { name: boot0,    address: 0x000000, size: 0x00C000 } # don't touch
  - { name: gpt,      address: 0x00C000, size: 0x004000 } # don't touch
  - { name: boot,     address: 0x010000, load_addr: 0x40000000, size: 0x030000 }
  - { name: imtb,     address: 0x040000, size: 0x002000 }
  - { name: prim,     address: 0x042000, load_addr: 0x40050000, size: 0x500000, verify: false, update: FULL, car: xz }
  - { name: lfs,      address: 0x542000, size: 0x600000, update: NONE } # NONE for ignore lfs ota
  - { name: misc,     address: 0xB42000, size: 0x410000 }
  - { name: kv,       address: 0xF52000, size: 0x004000 }
  - { name: kp,       address: 0xF56000, size: 0x001000 }
